const specialProduct = [
  {
    id: 1,
    name: "Netflix Premium",
    description: "4K Ultra HD streaming on up to 4 devices simultaneously",
    price: 100,
    billing_cycle: "monthly",
    image_url: "https://cdn-icons-png.flaticon.com/512/732/732228.png",
    stripe_price_id: "price_1RvMbRLYjp5zK6UojQQZ6Bbi",
  },
  {
    id: 2,
    name: "Spotify Family",
    description: "Ad-free music for up to 6 family members",
    price: 150,
    billing_cycle: "monthly",
    image_url: "https://cdn-icons-png.flaticon.com/512/2111/2111624.png",
    stripe_price_id: "price_1RstpgLYjp5zK6Uo1wflIU7e",
  },
  {
    id: 3,
    name: "Adobe Creative Cloud",
    description: "All Adobe creative apps including Photoshop and Premiere Pro",
    price: 120,
    billing_cycle: "monthly",
    image_url: "https://cdn-icons-png.flaticon.com/512/2702/2702602.png",
    stripe_price_id: "price_1Rstp7LYjp5zK6UoeW1V38Zx",
  },
  {
    id: 4,
    name: "Amazon Prime",
    description:
      "Free shipping, video streaming, and exclusive deals If you want, I can give you the perfect Tailwind class combination that keeps a nice width-to-height ratio on all devices without overflowing the screen.",
    price: 163,
    billing_cycle: "monthly",
    image_url: "https://cdn-icons-png.flaticon.com/512/731/731985.png",
    stripe_price_id: "price_1RvS6ELYjp5zK6Uo0PCwcF8Q",
  },
  {
    id: 5,
    name: "Microsoft 365 Family",
    description: "Office apps for up to 6 people with 1TB cloud storage each",
    price: 150,
    billing_cycle: "yearly",
    image_url: "https://cdn-icons-png.flaticon.com/512/732/732222.png",
    stripe_price_id: "price_1RxCTwLYjp5zK6UolPhvN9SO",
  },
  {
    id: 6,
    name: "Disney+ Bundle",
    description: "Disney+, Hulu, and ESPN+ with ads",
    price: 140,
    billing_cycle: "monthly",
    image_url: "https://cdn-icons-png.flaticon.com/512/5968/5968526.png",
  },
  {
    id: 7,
    name: "Peloton All-Access",
    description: "Unlimited access to Peloton's fitness classes",
    price: 200,
    billing_cycle: "monthly",
    image_url: "https://www.peloton.com/favicon.ico",
  },
  {
    id: 8,
    name: "Blue Apron",
    description: "Weekly meal kit delivery service",
    price: 260,
    billing_cycle: "weekly",
    image_url: "https://www.blueapron.com/favicon.ico",
  },
  {
    id: 9,
    name: "PlayStation Plus Premium",
    description: "Online multiplayer, monthly games, and classic catalog",
    price: 170,
    billing_cycle: "monthly",
    image_url: "https://cdn-icons-png.flaticon.com/512/731/731992.png",
  },
];

export default specialProduct;
