const specialProduct = [
  {
    id: 1,
    name: "Netflix Premium",
    description: "4K Ultra HD streaming on up to 4 devices simultaneously",
    price: 22.99,
    billing_cycle: "monthly",
    image_url: "https://cdn-icons-png.flaticon.com/512/732/732228.png",
  },
  {
    id: 2,
    name: "Spotify Family",
    description: "Ad-free music for up to 6 family members",
    price: 16.99,
    billing_cycle: "monthly",
    image_url: "https://cdn-icons-png.flaticon.com/512/2111/2111624.png",
  },
  {
    id: 3,
    name: "Adobe Creative Cloud",
    description: "All Adobe creative apps including Photoshop and Premiere Pro",
    price: 54.99,
    billing_cycle: "monthly",
    image_url: "https://cdn-icons-png.flaticon.com/512/2702/2702602.png",
  },
  {
    id: 4,
    name: "Amazon Prime",
    description: "Free shipping, video streaming, and exclusive deals",
    price: 14.99,
    billing_cycle: "monthly",
    image_url: "https://cdn-icons-png.flaticon.com/512/731/731985.png",
  },
  {
    id: 5,
    name: "Microsoft 365 Family",
    description: "Office apps for up to 6 people with 1TB cloud storage each",
    price: 99.99,
    billing_cycle: "yearly",
    image_url: "https://cdn-icons-png.flaticon.com/512/732/732222.png",
  },
  {
    id: 6,
    name: "Disney+ Bundle",
    description: "Disney+, Hulu, and ESPN+ with ads",
    price: 14.99,
    billing_cycle: "monthly",
    image_url: "https://cdn-icons-png.flaticon.com/512/5968/5968526.png",
  },
  {
    id: 7,
    name: "Peloton All-Access",
    description: "Unlimited access to Peloton's fitness classes",
    price: 44.0,
    billing_cycle: "monthly",
    image_url: "https://www.peloton.com/favicon.ico",
  },
  {
    id: 8,
    name: "Blue Apron",
    description: "Weekly meal kit delivery service",
    price: 59.94,
    billing_cycle: "weekly",
    image_url: "https://www.blueapron.com/favicon.ico",
  },
  {
    id: 9,
    name: "PlayStation Plus Premium",
    description: "Online multiplayer, monthly games, and classic catalog",
    price: 17.99,
    billing_cycle: "monthly",
    image_url: "https://cdn-icons-png.flaticon.com/512/731/731992.png",
  },
];

export default specialProduct;
